version: '3'

services:
  back:
    depends_on:
      - db
    build: ./back
    restart: always
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT

  db:
    container_name: 'database-node'
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    env_file: ./.env
    ports: 
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment: 
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - TZ=America/Sao_Paulo

volumes: 
  db: