version: "3"

services:
  # Serviço que irá rodar o node
  back:
    container_name: back
    depends_on:
      - db
    build: ./back
    restart: always
    ports:
      - 3001:3000
    # Configura as variáveis de ambiente dentro do container
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db # Nome do service logo abaixo
      NODE_PORT: '3001'

  # Serviço que irá rodar o banco de dados
  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306

# Lista de redes que os containeres irão utilizar
networks:
  # Rede padrão, criada automaticamente
  default:
    # Dá um nome específico à rede padrão
    name: store_manager_net

volumes:
  db: